/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f3f3",
        "slate-stone": "#708090",
        "primary-fixed": "#d2e4fb",
        "glacier-mint": "#7FFFD4",
        "background": "#f9f9f9",
        "error-container": "#ffdad6",
        "primary": "#041627",
        "secondary": "#50606f",
        "mint-glow": "rgba(127, 255, 212, 0.3)",
        "primary-container": "#1a2b3c",
        "surface-variant": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "secondary-fixed": "#d4e4f6",
        "surface-container": "#eeeeee",
        "surface-bright": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "secondary-container": "#d1e1f4",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1a1c1c",
        "outline-variant": "#c4c6cd",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#003023",
        "on-secondary-container": "#556474",
        "on-tertiary-container": "#00a47f",
        "on-error": "#ffffff",
        "on-surface-variant": "#44474c",
        "midnight-fjord": "#1A2B3C",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b8c8da",
        "on-primary-fixed-variant": "#38485a",
        "on-tertiary-fixed-variant": "#00513d",
        "on-secondary-fixed-variant": "#394857",
        "surface-dim": "#dadada",
        "on-tertiary-fixed": "#002117",
        "primary-fixed-dim": "#b7c8de",
        "tertiary": "#001911",
        "surface": "#f9f9f9",
        "cloud-white": "#F9F9F9",
        "inverse-surface": "#2f3131",
        "surface-container-highest": "#e2e2e2",
        "outline": "#74777d",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#5adcb3",
        "surface-tint": "#4f6073",
        "on-primary-container": "#8192a7",
        "inverse-primary": "#b7c8de",
        "on-primary-fixed": "#0b1d2d",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#79f9ce",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-fixed": "#0d1d2a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-md": "24px",
        "unit": "8px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "gutter": "24px",
        "container-max": "1200px"
      },
      fontFamily: {
        "body-md": ["var(--font-inter)"],
        "headline-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "headline-sm": ["var(--font-inter)"],
        "label-caps": ["var(--font-inter)"],
        "display-lg": ["var(--font-inter)"],
        "sans": ["var(--font-inter)"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};
